### ISSUE TITLE
Exception when tabulating empty data and using maxcolwidths

### ISSUE THREAD

**Issue by aantn** [astanin/python-tabulate#180]
```
File "/usr/local/lib/python3.9/site-packages/tabulate.py", line 1585, in tabulate
   num_cols = len(list_of_lists[0])
   IndexError: list index out of range
```

**Comment by astanin** [comment]
Can you please provide an example of the input data which triggers this exception?

```pycon
>>> tabulate([[]], maxcolwidths=5)
''
```

**Comment by aantn** [comment]
```python
>>> tabulate([])
''
>>> tabulate([], maxcolwidths=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/natanyellin/Library/Caches/pypoetry/virtualenvs/robusta-cli-k1xMhET--py3.9/lib/python3.9/site-packages/tabulate.py", line 1623, in tabulate
    num_cols = len(list_of_lists[0])
IndexError: list index out of range
```
