### ISSUE TITLE
Latest version fails at 'True', 'False'

### ISSUE THREAD

**Issue by mhuang001** [astanin/python-tabulate#189]
python3.8, commit [3f0757e](https://github.com/astanin/python-tabulate/commit/3f0757e117ed2ca1171bbf84b61793f353d67282)

```
>>> import tabulate

>>> print(tabulate.tabulate([['TRUE']], maxcolwidths=5))
----
TRUE
----

>>> print(tabulate.tabulate([['TRUE']], maxcolwidths=5))
----
TRUE
----

>>> print(tabulate.tabulate([['True']]))
----
True
----

>>> print(tabulate.tabulate([['True']], maxcolwidths=5))

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/cygdrive/d/data/tblt/python-tabulate/tabulate.py", line 1835, in tabulate
>     list_of_lists = _wrap_text_to_colwidths(
>   File "/cygdrive/d/data/tblt/python-tabulate/tabulate.py", line 1365, in _wrap_text_to_colwidths
>     wrapped = wrapper.wrap(casted_cell)
>   File "/usr/lib/python3.8/textwrap.py", line 351, in wrap
>     chunks = self._split_chunks(text)
>   File "/usr/lib/python3.8/textwrap.py", line 337, in _split_chunks
>     text = self._munge_whitespace(text)
>   File "/usr/lib/python3.8/textwrap.py", line 154, in _munge_whitespace
>     text = text.expandtabs(self.tabsize)
> AttributeError: 'bool' object has no attribute 'expandtabs'
> 

The apparent responsible code is https://github.com/astanin/python-tabulate/blob/3f0757e117ed2ca1171bbf84b61793f353d67282/tabulate.py#L1359-L1365

Might be related with #136.

**Comment by astanin** [comment]
Fixed in 0.10.0
