### ISSUE TITLE
Uncaught Python exception - ValueError: could not convert string to float: 'True'

### ISSUE THREAD

**Issue by astanin** [astanin/python-tabulate#209]
Fuzzer issue 50322

<html><body>

  | === Uncaught Python exception: ===
-- | --
  | ValueError: could not convert string to float: 'True'
  | Traceback (most recent call last):
  | File "fuzz_tabulate.py", line 37, in TestOneInput
  | File "tabulate/__init__.py", line 2171, in tabulate
  | File "tabulate/__init__.py", line 2172, in &lt;listcomp&gt;
  | File "tabulate/__init__.py", line 2172, in &lt;listcomp&gt;
  | File "tabulate/__init__.py", line 1239, in _format

</body>
</html>

**Comment by astanin** [comment]
Probably related: #189

**Comment by jimmyzzxhlh** [comment]
Hi @astanin, is it possible to fix this issue? We are running into this issue in a production and would love to see https://github.com/astanin/python-tabulate/pull/236 being reviewed and merged.
