### ISSUE TITLE
tabulate raises IndexError for empty data if maxcolwidths is specified 

### ISSUE THREAD

**Issue by xcharleslin** [astanin/python-tabulate#223]
Repro:
```python
>>> from tabulate import tabulate
>>> tabulate([])
''

>>> tabulate([], maxcolwidths=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orbit/.local/lib/python3.9/site-packages/tabulate/__init__.py", line 2054, in tabulate
    num_cols = len(list_of_lists[0])
IndexError: list index out of range

>>> tabulate({'A': []}, maxcolwidths=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orbit/.local/lib/python3.9/site-packages/tabulate/__init__.py", line 2054, in tabulate
    num_cols = len(list_of_lists[0])
IndexError: list index out of range
```

**Comment by eliegoudout** [comment]
Fixes from #221 correct these errors:
```
>>> print(tabulate([], maxcolwidths=10))

>>> print(tabulate({'A': []}, maxcolwidths=10))

```
