### ISSUE TITLE
[bug] Handling NoneTypes while using the maxcolwidths feature

### ISSUE THREAD

**Issue by f0sh** [astanin/python-tabulate#271]
Using a dataset, which contains a field with a None type and a defined maxcolwidths for that field - like the following:

```
headers= ['id', 'name', 'description']
width = [None, None, 5]
data = [[123456, 'Test 1', 'Testdescription'], [654321, 'Test 2', None]]
```

 leads to `TypeError: NoneType takes no arguments` error.

**Traceback**

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\project\package\script.py", line 21, in <module>
    main()
  File "C:\Users\user\project\package\script.py", line 18, in main
    cli()
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\project\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\project\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\user\project\package\commands_model.py", line 181, in list_elements
    click.echo(tabulate(data, headers=headers, tablefmt="simple_grid", maxcolwidths=width))
  File "C:\Users\user\project\lib\site-packages\tabulate\__init__.py", line 2061, in tabulate
    list_of_lists = _wrap_text_to_colwidths(
  File "C:\Users\user\project\lib\site-packages\tabulate\__init__.py", line 1516, in _wrap_text_to_colwidths
    str(cell) if _isnumber(cell) else _type(cell, numparse)(cell)
TypeError: NoneType takes no arguments
```

**Temporary Solution**

You manually have to check the dataset and replace None Types with empty strings before passing it to tabulate. Would be better if tabulate could handle NoneTypes by itself.

**Comment by AlecVivian** [comment]
In the meantime I'll attempt monkey patching these functions, but a solution that is working for my edge case is to modify the function `_wrap_text_to_colwidths` to take in optional kwarg `missingval`, and use that value in a situation where decorator `_type` can't operate on a cell's value:
https://github.com/astanin/python-tabulate/blob/master/tabulate/__init__.py#L1532

```python
def _wrap_text_to_colwidths(list_of_lists, colwidths, missingval='__ERR_VAL__', numparses=True): # add `missingval` as optional param
    numparses = _expand_iterable(numparses, len(list_of_lists[0]), True)

    result = []

    for row in list_of_lists:
        new_row = []
        for cell, width, numparse in zip(row, colwidths, numparses):
            if _isnumber(cell) and numparse:
                new_row.append(cell)
                continue

            if width is not None:
                wrapper = _CustomTextWrap(width=width)
                # Cast based on our internal type handling
                # Any future custom formatting of types (such as datetimes)
                # may need to be more explicit than just `str` of the object
                casted_cell = (
                    str(cell) if _isnumber(cell) else _type(cell, numparse)(cell) if cell is not None else missingval # circumvent applying the operation on NoneType.
                )
                wrapped = wrapper.wrap(casted_cell)
                new_row.append("\n".join(wrapped))
            else:
                new_row.append(cell)
        result.append(new_row)

    return result
```

Then in the main `tabulate` function (https://github.com/astanin/python-tabulate/blob/master/tabulate/__init__.py#L2093-L2120 ):

```python
def tabulate(...):
    ...
    if maxcolwidths is not None:
        if len(list_of_lists):
            num_cols = len(list_of_lists[0])
        else:
            num_cols = 0
        if isinstance(maxcolwidths, int):  # Expand scalar for all columns
            maxcolwidths = _expand_iterable(maxcolwidths, num_cols, maxcolwidths)
        else:  # Ignore col width for any 'trailing' columns
            maxcolwidths = _expand_iterable(maxcolwidths, num_cols, None)

        numparses = _expand_numparse(disable_numparse, num_cols)
        list_of_lists = _wrap_text_to_colwidths(
            list_of_lists, maxcolwidths, missingval, numparses=numparses # Utilize missingval as substitute for None values.
        )

    if maxheadercolwidths is not None:
        num_cols = len(list_of_lists[0])
        if isinstance(maxheadercolwidths, int):  # Expand scalar for all columns
            maxheadercolwidths = _expand_iterable(
                maxheadercolwidths, num_cols, maxheadercolwidths
            )
        else:  # Ignore col width for any 'trailing' columns
            maxheadercolwidths = _expand_iterable(maxheadercolwidths, num_cols, None)

        numparses = _expand_numparse(disable_numparse, num_cols)
        headers = _wrap_text_to_colwidths(
            [headers], maxheadercolwidths, numparses=numparses # Assume default value specified in private function sig.
        )[0]
    ...
```

**Comment by wabiloo** [comment]
I'm having the same issue. I will try the monkeypatch, but a core solution would be great, thanks!

**Comment by mp-gh** [comment]
I'm running into this as well:
>>> from tabulate import tabulate
>>> config_table_data = list()
>>> config_table_data.append(("a","value"))
>>> config_table_data.append(("b",None))
>>> print(tabulate(config_table_data))
-  -----
a  value
b
-  -----
>>> print(tabulate(config_table_data,maxcolwidths=[20, 30]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mp/.cache/virtualenvs/hga6bo9e-py3.10/lib/python3.10/site-packages/tabulate/__init__.py", line 2061, in tabulate
    list_of_lists = _wrap_text_to_colwidths(
  File "/home/mp/.cache/virtualenvs/hga6bo9e-py3.10/lib/python3.10/site-packages/tabulate/__init__.py", line 1516, in _wrap_text_to_colwidths
    str(cell) if _isnumber(cell) else _type(cell, numparse)(cell)
TypeError: NoneType takes no arguments
>>>

**Comment by astanin** [comment]
Resolved in v0.10.0
