### ISSUE TITLE
Incompatibility with Python 3.11

### ISSUE THREAD

**Issue by Anthirian** [astanin/python-tabulate#278]
Version 0.9.0 is not compatible with Python 3.11. When importing the module the following stack trace is shown.

```python
$ python3
Python 3.11.4 (main, Jun 28 2023, 19:51:46) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tabulate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geert/.local/lib/python3.11/site-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)
```

As can be seen in the [release notes](https://docs.python.org/3/whatsnew/3.10.html#removed), the `Iterable` abstract class was removed from `collections`:
> - Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue?@action=redirect&bpo=37324).)

**Comment by kotborealis** [comment]
Should be already fixed, version from pip imports `Iterable` from `collections.abc`
![image](https://github.com/astanin/python-tabulate/assets/6463851/a8136241-6a29-4316-94dd-c90774adf745)
