### ISSUE TITLE
When using maxcolwidths in a column that contains None values, tabulate crashes with "NoneType takes no arguments"

### ISSUE THREAD

**Issue by gschizas** [astanin/python-tabulate#312]
Sample script:

```
from tabulate import tabulate
table = [["spam", 41.9999], ["eggs", "451.0"], ["sausages", None]]
print(tabulate(table, headers='keys', tablefmt='plain'))
print(tabulate(table, headers='keys', tablefmt='plain', maxcolwidths=40))

```

The last line leads to this exception:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(tabulate(table, headers='keys', tablefmt='plain', maxcolwidths=40))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tabulate/__init__.py", line 2061, in tabulate
    list_of_lists = _wrap_text_to_colwidths(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "tabulate/__init__.py", line 1516, in _wrap_text_to_colwidths
    str(cell) if _isnumber(cell) else _type(cell, numparse)(cell)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NoneType takes no arguments
```

(from version 0.90, in the latest commit only the line numbers change)

This is a simple fix, line 1516 (for v0.9.0) should have another guard, like so:

```
'' if cell is None else str(cell) if _isnumber(cell) else _type(cell, numparse)(cell)
```

I'll do a PR soon.

**Comment by fradeve** [comment]
Thanks for fixing this! I have the same issue :smile:

**Comment by tywallis** [comment]
I am still having this issue

**Comment by gschizas** [comment]
> I am still having this issue

Well, it hasn't been merged or published, what did you expect? 😄

**Comment by RaSan147** [comment]
Thanks good sir

**Comment by AdityaMayukhSom** [comment]
I think the pull request is still under review, any updates on the feedback implementation?

**Comment by gschizas** [comment]
It is, but at least @astanin has been committing again, so I have _some_ hope.

**Comment by cooper2k4** [comment]
I'm just having the same issue here now. It doesn't seem to be committed? 🤔

**Comment by RaSan147** [comment]
Finally, after long long later. Its merged.
