### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by Delta456** [astanin/python-tabulate#32]
**Version** 
Python 3.8.1

**What did you do?**
`pip3 install tabulate` 

**What did you expected to see?**
Installed successfully

**What did you see instead**

```error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\home\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-install-0lcew9df\\tabulate\\setup.py'"'"'; __file__='"'"'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-install-0lcew9df\\tabulate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Home\AppData\Local\Temp\pip-install-0lcew9df\tabulate\pip-egg-info'
         cwd: C:\Users\Home\AppData\Local\Temp\pip-install-0lcew9df\tabulate\
    Complete output (26 lines):
    Traceback (most recent call last):
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2798, in get_entry_map
        ep_map = self._ep_map
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2756, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Home\AppData\Local\Temp\pip-install-0lcew9df\tabulate\setup.py", line 64, in <module>
        test_suite="nose.collector",
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 133, in _install_setup_requires
        (k, v) for k, v in attrs.items()
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 444, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 656, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2801, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "c:\users\home\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2499, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by astanin** [comment]
> Python 3.8.1

> command: 'c:\users\home\appdata\local\programs\python\python37\python.exe'

You reported a problem with Python 3.8.1 but the logs show that Python 3.7 is called.
Please check all your Python installations and PATH.

**Comment by astanin** [comment]
I just checked. Vanilla Python 3.8.1 distribution on Windows 10 x64, pip install tabulate works.
