### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by charliemb2** [astanin/python-tabulate#327]
Many or most table formats (tablefmt=) experience the following error when redirecting outputs to STDOUT by using the > character on the command line. 

```
Traceback (most recent call last):
  File "c:\Py.cmb\tables\table_try.py", line 66, in <module>
    print(tabulate(list_o_lists,
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-92: character maps to <undefined>
```
The default table format works, as do some simple ones like `pipe`, `outline`.  But at least the following exhibit the same or similar error,  `rounded_outline`, `simple_outline`, `fancy_outline`, and `heavy_outline`.

Probably related to these failing table formats is that `\n` newline characters within cells don't format properly.  However, the documentation hints at this stating: `Most table formats support multiline cell text (text containing newline characters). The newline characters are honored as line break characters.`  "Most" being the operative word.  However, I mention it because it may be possible to hit two birds with one stone.

Environment
--------------
Windows 10 Pro
Python 3.10
Windows Powershell

Expected behavior:  
---------------------
I'd expect the tabulate to at least fall back to a simpler perhaps default table even this this isn't planned on being fixed.  However ideally, this could be fixed and if it can be it should be.

**Comment by charliemb2** [comment]
[redirect_to_stdout_for_error.zip](https://github.com/astanin/python-tabulate/files/15457885/redirect_to_stdout_for_error.zip)

**Comment by charliemb2** [comment]
Thanks!  Off to v0.10.0 we go.
